Script started on Fri Feb  5 19:06:47 2021
[?1034hbash-4.2$ cd ~/cs161/root
bash-4.2$ ./sys161 kernel
sys161: System/161 release 1.14, compiled Feb  5 2021 17:13:49

OS/161 base system version 1.10
Copyright (c) 2000, 2001, 2002, 2003
   President and Fellows of Harvard College.  All rights reserved.

Put-your-group-name-here's system version 0 (ASST0 #1)

Cpu is MIPS r2000/r3000
1872k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
hardclock on ltimer0 (100 hz)
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lser0 at lamebus0
con0 at lser0
pseudorand0 (virtual)

OS/161 kernel [? for menu]: p /sni  bin/poweriff   off
Operation took 0.000162800 seconds
OS/161 kernel [? for menu]: Shutting down.
The system is halted.
sys161: 315804196 cycles (4331751k, 18u, 311472427i)
sys161: 1917 irqs 6 exns 0r/0w disk 27r/678w console 8r/0w/3m emufs 0r/0w net
sys161: Elapsed real time: 12.626391 seconds (25.0114 mhz)
sys161: Elapsed virtual time: 12.632167840 seconds (25 mhz)
bash-4.2$ exit
exit

Script done on Fri Feb  5 19:07:22 2021
